// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXvORto7nFHuiRGaDx75e0OX0Tod0Plf4',
    appId: '1:108605218784:web:18d9aa1e370c141311d585',
    messagingSenderId: '108605218784',
    projectId: 'mut-is',
    authDomain: 'mut-is.firebaseapp.com',
    storageBucket: 'mut-is.appspot.com',
    measurementId: 'G-07QF40P6TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIZuFOEoYIsH1H92b6pXEPfewBVkTmmYs',
    appId: '1:108605218784:android:699e4e64b1d6840911d585',
    messagingSenderId: '108605218784',
    projectId: 'mut-is',
    storageBucket: 'mut-is.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuXwS_vZ0R0srLDI30fLNBSFKfGlsAmTg',
    appId: '1:108605218784:ios:3d173e9be03d6fce11d585',
    messagingSenderId: '108605218784',
    projectId: 'mut-is',
    storageBucket: 'mut-is.appspot.com',
    iosClientId: '108605218784-40p9481bh0njmmj63ertgqh4eko9fd5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.myEnglishStory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuXwS_vZ0R0srLDI30fLNBSFKfGlsAmTg',
    appId: '1:108605218784:ios:3d173e9be03d6fce11d585',
    messagingSenderId: '108605218784',
    projectId: 'mut-is',
    storageBucket: 'mut-is.appspot.com',
    iosClientId: '108605218784-40p9481bh0njmmj63ertgqh4eko9fd5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.myEnglishStory',
  );
}
